name: OWASP ZAP Baseline Scan
description: 'Perform a baseline scan of 50 common security items on a target site'
inputs:
  target:
    description: 'target of the scan'
    required: true

jobs:
 build:

    runs-on: ubuntu-latest
  
    steps:    
    - name: Run the OWASP baseline scanner
      run: docker run -t owasp/zap2docker-weekly zap-baseline.py -t {{inputs.target}} | tee zapScanResults.txt
    - name: Upload scan results
      uses: actions/upload-artifact@v1
      with:
          name: zapScanResults
          path: zapScanResults.txt
    - name: Get result summary
      id: result_summary
      run: echo "##[set-output name=value;]$(cat zapScanResults.txt | tail -1)"